
###################
### Imports
###################

## Standard Library
import os
import sys
import json
import gzip
from glob import glob
from datetime import datetime
from collections import Counter
from functools import partial
from itertools import product

## External Library
import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
from multiprocessing import Pool
from scipy.sparse import vstack
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import metrics

## Local
from mhlib.util.helpers import flatten
from mhlib.preprocess.tokenizer import Tokenizer

###################
### Helpers
###################

def get_subreddit_counts(filename,
                         min_date=None,
                         max_date=None):
    """

    """
    ## Load Data
    with gzip.open(filename, "r") as the_file:
        data = json.load(the_file)
    ## Filter By Time
    if min_date is not None and isinstance(min_date,str):
        min_date=pd.to_datetime(min_date)
    if max_date is not None and isinstance(max_date,str):
        max_date=pd.to_datetime(max_date)
    filtered_data = []
    for d in data:
        tstamp = datetime.fromtimestamp(d["created_utc"])
        if min_date is not None and tstamp < min_date:
            continue
        if max_date is not None and tstamp > max_date:
            continue
        filtered_data.append(d)
    ## Count
    counts = Counter(list(map(lambda d: d["subreddit"], filtered_data)))
    return filename, counts

def create_dict_vectorizer(vocab_terms):
    """

    """
    ngram_to_idx = dict((n, i) for i, n in enumerate(sorted(vocab_terms)))
    _count2vec = DictVectorizer(separator=":")
    _count2vec.vocabulary_ = ngram_to_idx.copy()
    rev_dict = dict((y, x) for x, y in ngram_to_idx.items())
    _count2vec.feature_names_ = [rev_dict[i] for i in range(len(rev_dict))]
    return _count2vec

def pattern_match(string, patterns):
    """

    """
    string_lower = string.lower()
    for p in patterns:
        if p in string_lower:
            return True
    return False

def get_language_counts(filename,
                        filtered_subs=set(),
                        filtered_language=set(),
                        min_date=None,
                        max_date=None):
    """

    """
    ## Load
    with gzip.open(filename, "r") as the_file:
        data = json.load(the_file)
    ## Date Boundary Formatting
    if min_date is not None and isinstance(min_date,str):
        min_date=pd.to_datetime(min_date)
    if max_date is not None and isinstance(max_date,str):
        max_date=pd.to_datetime(max_date)
    ## Filtering
    filtered_data = []
    for d in data:
        ## Apply Subreddit Filter
        if d["subreddit"].lower() in filtered_subs:
            continue
        ## Apply Language Filter
        if pattern_match(d["text"], filtered_language):
            continue
        ## Apply Date Filters
        tstamp = datetime.fromtimestamp(d["created_utc"])
        if min_date is not None and tstamp < min_date:
            continue
        if max_date is not None and tstamp > max_date:
            continue
        ## Add Data to Filtered List
        filtered_data.append(d)
    ## Tokenization
    tokens = list(map(lambda t: TOKENIZER.tokenize(t["text"]), filtered_data))
    ## Count Vocab
    token_counts = Counter(flatten(tokens))
    return filename, token_counts

###################
### Language Patterns
###################

## Georgetown Expansion Mapping
GEORGETOWN_EXPANSION_MAPPING = \
        {
            "_condition": [
                "adhd",
                "bipolar",
                "clinical depression",
                "depresion",
                "depression",
                "depressive disorder",
                "first depression",
                "first major depression",
                "major depression",
                "major depressive",
                "mental disorder",
                "mental disorders",
                "mental illness",
                "mild depression",
                "mild depressive",
                "ptsd",
                "severe depression",
                "severe mental illness"
            ],
            "_doctor": [
                "clinically",
                "doc",
                "doctor",
                "dr",
                "formally",
                "medically",
                "official",
                "officially",
                "professionally",
                "proper",
                "properly",
                "psych",
                "psychiatric",
                "psychiatrist",
                "psychologist",
                "shrink",
                "therapist"
            ],
            "_ref": [
                "aunt",
                "aunty",
                "baby",
                "boy",
                "brother",
                "child",
                "cousin",
                "dad",
                "daughter",
                "father",
                "friend",
                "friend of mine",
                "friends",
                "girl",
                "grandfather",
                "grandmother",
                "he",
                "he's",
                "her",
                "hers",
                "him",
                "his",
                "husband",
                "mom",
                "mother",
                "people",
                "persons",
                "she",
                "she's",
                "sister",
                "son",
                "their",
                "uncle",
                "wife"
            ]
        }

def create_rsdd_language_patterns(use_mh=True,
                                  use_pos=False,
                                  use_neg=False):
    """

    """
    ## Specific Mental Health Terms
    mh_terms = [
                "adhd",
                "attention deficit hyperactivity disorder",
                "bi polar",
                "bi-polar",
                "bipolar",
                "depres",
                "depresion",
                "depression",
                "depressive",
                "diagnos",
                "mdd",
                "mental disorder",
                "mental illness",
                "post traumatic stress disorder",
                "post-traumatic stress disorder",
                "posttraumatic stress disorder",
                "ptsd",
                "suffer from",
                "suffering from",
                   ]
    ## Negative Diagnosis Patterns
    neg_patterns = [
            "any help diagnos",
            "bever gad duagbis",
            "chooses not to be diagnos",
            "costs associated with diagnos",
            "diagnos her",
            "diagnos people",
            "diagnostic analysis",
            "diagnostics",
            "diagnostic test",
            "fear a diagnos",
            "have never sought diagnos",
            "have not been diagnos",
            "haven't been diagnos",
            "help me diagnos",
            "her recent cancer diagnos",
            "he's diagnos",
            "how you get diagnos",
            "i almost wish i had a _condition diagnosis",
            "i don't expect a diagnos",
            "i dont have any diagnos",
            "i hadn't been diagnos",
            "i have not been diagnos",
            "i haven't been diagnos",
            "i'll be diagnos",
            "i'm not a diagnos",
            "never actually diagnosed",
            "never been diagnos",
            "never been officially diagnos",
            "never clinically diagnos",
            "never diagnosed me",
            "no diagnos",
            "no formal diagnos",
            "nor am i diagnos",
            "not diagnos",
            "not formally diagnos",
            "not looking for a diagnos",
            "not received any diagnos",
            "not technically diagnosed",
            "not yet diagnos",
            "policy against diagnosis",
            "_ref been diagnos",
            "_ref being dianos",
            "_ref currently doesn't have a diagnos",
            "_ref does have diagnos",
            "_ref got diagnos",
            "_ref has been diagnos",
            "_ref has been dianos",
            "_ref has been recently dianos",
            "_ref has recently been diagnos",
            "_ref is diagnos",
            "_ref was just dianos",
            "_ref was then diagnos",
            "self diagnos",
            "she's diagnos",
            "they were diagnos",
            "this is an informal diagnosis",
            "this is a self diagnosis",
            "this is a self-diagnosis",
            "to be diagnos",
            "to diagnose or fix",
            "to get a diagnos",
            "trying to get diagnos",
            "until i get diagnos",
            "wasn't actually diagnos",
            "wasn't clinically diagnos",
            "wasn't diagnos",
            "wasn't formally diagnos",
            "what is your diagnos",
            "who has been diagnos",
            "who have actually been diagnos",
            "who have been diagnos",
            "you can't diagnose me",
            "you can't make a diagnosis",
            "you guys can't diagnose me",
            ]
    ## Positive Diagnosis Patterns
    pos_patterns = ['after my diagnos',
                    'as someone with a diagnos',
                    'depressive episode that got me diagnosed',
                    '_doctor diagnosed me',
                    '_doctor has diagnosed my',
                    '_doctor who diagnosed and medicated me',
                    'following my diagnos',
                    'he diagnosed me',
                    'he just diagnosed me',
                    'he recently diagnosed me',
                    'i also have been diagnos',
                    'i also have diagnosed _condition',
                    'i am diagnosed _condition',
                    'i am diagnosed with',
                    'i am _doctor diagnosed',
                    'i am recently diagnosed',
                    'i became sick and was diagnosed',
                    'i ended up being diagnosed',
                    'i eventually got a diagnosis',
                    'i even went to a _doctor and got diagnosed',
                    'i even went to the _doctor and got diagnosed',
                    'i finally got a diagnosis',
                    'i got a _condition diagnos',
                    'i got a _doctor diagnos',
                    'i got _condition diagnos',
                    'i got _condition diagnosis',
                    'i got diagnos',
                    'i got my diagnosis of',
                    'i got sick and was diagnosed',
                    'i had a _doctor diagnose me',
                    'i had already been diagnosed',
                    'i had been diagnosed',
                    'i had gotten the diagnosis',
                    'i have a _condition diagnos',
                    'i have a _condition diagnosis',
                    'i have a couple _condition diagnos',
                    'i have a diagnos',
                    'i have also been diagnosed',
                    'i have been _condition with a diagnosis',
                    'i have been _condition, with a diagnosis',
                    'i have been diagnos',
                    'i have been diagnosed',
                    'i have been _doctor diagnos',
                    'i have been previously diagnosed',
                    'i have been recently diagnos',
                    'i have _condition diagnosed',
                    'i have _condition, diagnosed',
                    'i have _condition which was only recently diagnosed',
                    'i have _condition, which was only recently diagnosed',
                    'i have _condition which was recently diagnosed',
                    'i have _condition, which was recently diagnosed',
                    'i have diagnos',
                    'i have diagnosed _condition',
                    'i have _doctor diagnosed',
                    'i have ended up being diagnosed',
                    'i have had diagnosed',
                    'i have honestly diagnosed',
                    'i have many _condition diagnosed',
                    'i have many other _condition diagnosed',
                    'i have only recently been diagnos',
                    'i have recently been diagnos',
                    'i have several _condition diagnosed',
                    'i have several other _condition diagnosed',
                    'i just got diagnos',
                    "i'm also diagnos",
                    "i'm diagnos",
                    'im diagnos',
                    "i'm recently diagnosed",
                    "i'm very recently diagnosed",
                    'i only got diagnos',
                    'i received the diagnosis',
                    'i saw a _doctor after being diagnosed',
                    'i suffer from clinically diagnos',
                    'i suffer from diagnos',
                    "i've a _condition diagnosis",
                    "i've already been diagnosed",
                    "i've been depressed and diagnosed",
                    "i've been diagnos",
                    "i've been diagnosed",
                    "i've been diagnosed with",
                    "i've been _doctor diagnos",
                    "i've been recently diagnos",
                    "i've been seeing a _doctor and been diagnos",
                    "i've been struggling with my diagnosis",
                    "i've got a _condition diagnosis",
                    "i've just been diagnos",
                    "i've only been diagnos",
                    "i've only recently been diagnos",
                    "i've recently been diagnos",
                    "i've since been diagnosed",
                    "i've suffered with diagnosed",
                    "i've tried after being diagnosed",
                    "i've tried after my diagnosis",
                    "i've tried since being diagnosed",
                    "i've tried since my diagnosis",
                    'i was also diagnosed',
                    'i was diagnos',
                    'i was diagnosed with',
                    'i was _doctor diagnos',
                    'i was eventually diagnosed',
                    'i was first diagnos',
                    'i was given a diagnos',
                    'i was just diagnos',
                    'i was originally diagnosed',
                    'i was recently diagnos',
                    'i was then diagnosed with',
                    'i was ultimately diagnosed',
                    'i was very recently diagnosed',
                    'i went to a _doctor and got diagnosed',
                    'i went to _doctor get diagnosed',
                    'i went to _doctor, get diagnosed',
                    'i went to _doctor got diagnosed',
                    'i went to _doctor, got diagnosed',
                    'i went to see a _doctor was diagnosed',
                    'i went to see a _doctor, was diagnosed',
                    'i went to the _doctor and got diagnosed',
                    'i went to the _doctor get diagnosed',
                    'i went to the _doctor, get diagnosed',
                    'i went to the _doctor got diagnosed',
                    'i went to the _doctor, got diagnosed',
                    'last year i was diagnos',
                    'led my _doctor to my current diagnosis',
                    'led my _doctor to my diagnosis',
                    'mine is diagnosed',
                    'my _condition diagnosis',
                    'my doctor diagnosed me',
                    'my _doctor diagnosis',
                    'my _doctor has diagnosed me',
                    'my official diagnosis of',
                    'my only _doctor diagnosis',
                    'my recent diagnosis',
                    'my recently diagnosed _condition',
                    'only recently have i been diagnos',
                    'recently diagnosed me as',
                    'she diagnosed me',
                    'she just diagnosed me',
                    'she recently diagnosed me',
                    "since being diagnosed i've",
                    "since diagnosed i've",
                    'they diagnosed me',
                    'they diagnosed me with',
                    'they just diagnosed me',
                    'they recently diagnosed me',
                    'until i was diagnosed this year',
                    'who diagnosed me']
    ## Expand Patterns
    all_patterns = []
    if use_mh:
        all_patterns.extend(mh_terms)
    psets = []
    if use_pos:
        psets.append(pos_patterns)
    if use_neg:
        psets.append(neg_patterns)
    for pset in psets:
        for p in pset:
            if "_" in p:
               p_sep = p.split()
               n = len(p_sep) - 1
               exp_match = [i for i, j in enumerate(p_sep) if j.startswith("_")][0]
               exp_match_fillers = GEORGETOWN_EXPANSION_MAPPING[p_sep[exp_match].rstrip(",")]
               for emf in exp_match_fillers:
                   if p_sep[exp_match].endswith(","):
                       emf += ","
                   emf_pat = " ".join(p_sep[:exp_match] + [emf] + p_sep[min(n, exp_match+1):])
                   all_patterns.append(emf_pat)
            else:
                all_patterns.append(p)
    all_patterns = set(all_patterns)
    return all_patterns

def create_smhd_language_patterns(use_mh=True,
                                  use_pos=False,
                                  use_neg=False):
    """

    """
    ## Mental Health Terms
    mh_terms = ['add',
                'anxiety',
                'add attention deficit disorder',
                'addh',
                'adhd',
                'adhd',
                'adhd',
                'adhd',
                'a.d.h.d.',
                'ad/hd',
                'adhd/add',
                'adhd (attention deficit hyperactivity disorder)',
                'adhd combined type',
                'adhd predominantly hyperactive',
                'adult-onset add',
                'affective bipolar disorder',
                'alternating insanity',
                'anancastic neurosis',
                'anancastic personality',
                'anankastic personality',
                'anankastic personality disorder',
                'anorectic',
                'anorexi',
                'anorexia',
                'anorexia',
                'anorexias',
                'anorexic',
                'anxiety',
                'anxiety disorder',
                'anxiety disorder',
                'anxietydisorderautism',
                'anxiety disorder generalize',
                'anxiety disorder nos',
                'anxiety disorder separation',
                'anxiety disorder social',
                'anxiety disorer',
                'anxiety neurosis',
                'anxiety separation',
                'anxiety separation disorder',
                'anxiety social',
                'anxity disorder',
                "apserger's",
                'apsergers syndrome',
                'asberger',
                'asberger disorder',
                'asbergers',
                "asberger's",
                "asberger's disorder",
                'asbergers disorder',
                "asberger's syndrome",
                'asbergers syndrome',
                'asberger syndrome',
                'asburger',
                "asburger's syndrome",
                'asburger syndrome',
                'aspberger',
                "aspberger's",
                "aspberger's syndrome",
                'aspberger syndrome',
                "asperberger's syndrome",
                'asperger',
                'asperger disorder',
                'aspergers',
                'aspergers',
                "asperger's",
                "asperger's disease",
                'asperger s disorder',
                "asperger's disorder",
                'aspergers disorder',
                'aspergers symptoms',
                "asperger's syndome",
                'aspergers syndrom',
                'asperger s syndrome',
                "asperger's syndrome",
                'aspergers syndrome',
                'asperger syndrome',
                'aspergian',
                'aspergic',
                'aspie',
                'aspies',
                'aspurger',
                'assberger',
                'assburger',
                'assburgers',
                "assburger's",
                "assburger's syndrome",
                'assburgers syndrome',
                'assburger syndrome',
                'attention defecit disorder',
                'attention deficiency disorder',
                'attention deficiency hyperactivity disorder',
                'attention deficiency/hyperactivity disorder',
                'attention deficiency hyperactivity syndrome',
                'attention deficiency/hyperactivity syndrome',
                'attention deficiency syndrome',
                'attention deficit dis',
                'attention deficit disorder',
                'attention-deficit disorder',
                'attention deficit disorder add',
                'attention-deficit disorder (add adhd)',
                'attention deficit disorder of childhood with hyperactivity',
                'attention deficit disorder with hyperactivity',
                'attention deficit dis with hyperactivity',
                'attention deficit hyperactive disorder',
                'attention-deficit hyperactive disorder',
                'attention deficit hyperactive syndrome',
                'attention deficit hyperactivity dis',
                'attention deficit hyperactivity disorder',
                'attention deficit hyperactivity disorder',
                'attention deficit-hyperactivity disorder',
                'attention deficit/hyperactivity disorder',
                'attention-deficit hyperactivity disorder',
                'attention-deficit/hyperactivity disorder',
                'attention deficit hyperactivity disorder adhd',
                'attention deficit hyperactivity disorder (adhd)',
                'attention deficit-hyperactivity disorder (adhd)',
                'attention deficit hyperactivity disorder nos',
                'attention-deficit hyperactivity syndrome',
                'attention deficit hyper disorder',
                'attention deficit(hyper) disorder',
                'attention deficits disorder hyper',
                'attention deficit syndrome',
                'attention deficit w/ hyperactivity',
                'attention deflict distorder',
                'attn deficit w hyperact',
                'auspergers',
                "ausperger's syndrome",
                'auspergers syndrome',
                'austism',
                'austistic',
                'authism',
                'authistic',
                'autisim',
                'autism',
                'autismos',
                'autisms',
                'autism spectrum dis',
                'autism spectrum disoder',
                'autism spectrum disorder',
                'autism spectrum disorder',
                'autism spectrum disorders',
                'autistic',
                'autistic',
                'autistic disorder',
                'autistic spectrum disorder',
                'autisum spectrum disorder',
                'bi 1',
                'bi 2',
                'binge eating',
                'binge eating disorder',
                'binge-eating disorder',
                'binge-eating disorder',
                'biopolar disorder',
                'bipola',
                'bipolar',
                'bipolar',
                'bipolar',
                'bi polar',
                'bi polar',
                'bi-polar',
                'bi-polar',
                'bipolar1',
                'bipolar 1',
                'bipolar2',
                'bipolar 2',
                'bipolar affective disease',
                'bipolar affective disorder',
                'bipolar affective psychosis',
                'bipolar depression',
                'bipolar diorder',
                'bipolar dis',
                'bipolar disoder',
                'bi polar disorder',
                'bi-polar disorder',
                'bipolar disorder',
                'bipolar disorder',
                'bipolar disorder nos',
                'bipolar disoreder',
                'bipolari',
                'bipolarii',
                'bi-polar illness',
                'bipolar illness',
                'bipolarism',
                'bipolar mania',
                'bipolar mental disorder',
                'bipolar mood disorder',
                'bipolar personality disorder',
                'bipolars',
                'bipolat',
                'bi-poler disorder',
                'bipoloar disorder',
                'bolemia',
                'bp1',
                'bp2',
                'bpd1',
                'bpd 1',
                'bpd2',
                'bpd 2',
                'bpdi',
                'bpd i',
                'bpdii',
                'bpd ii',
                'bulemia',
                'bulemic',
                'bulimea',
                'bulimia',
                'bulimia',
                'bulimia nervosa',
                'bulimias',
                'bulimic',
                'bullemia',
                'child adhd',
                'child autism',
                'childhood adhd',
                'childhood attention deficit/hyperactivity disorder',
                'childhood autism',
                'childhood separation anxiety',
                'chronic depression',
                'circular insanity',
                'clincal depression',
                'clinical anxiety',
                'clinical depressed',
                'clinical depression',
                'clinical depression',
                'clinically depressed',
                'combat neurosis',
                'complex ptsd',
                'complex trauma disorderschizophrenia',
                'cptsd',
                'cyclophrenia',
                'cyclophrenia',
                'cyclophrenic',
                'cyclothymia',
                'cyclothymia',
                'cyclothymia disorder',
                'cyclothymic',
                'cyclothymic dis',
                'cyclothymic disorder',
                'cyclothymic disorders',
                'deppression',
                'depres',
                'depresion',
                'depresion',
                'depressed',
                'depressiion',
                'depressio',
                'depressiom',
                'depression',
                'depression',
                'depression clinical',
                'depression mental',
                'depressions',
                'depression unipolar',
                'depressive',
                'depressive',
                'depressive dis',
                'depressive dis major',
                'depressive disorder',
                'depressive disorder',
                'depressive disorder major',
                'depressive disorder nos',
                'depressive episode',
                'depressive illness',
                'depressive neuroses',
                'depressive neurosis',
                'depresssion',
                'diagnos',
                'dipolar',
                'disorder depressive',
                'disorder dysphoric premenstrual',
                'disorder generalized anxiety',
                'disorder premenstrual dysphoric',
                'disorder social phobia',
                'disthymia',
                'distimea',
                'distimia',
                'double depression',
                'dpression',
                'dual-form insanity',
                'dysthemia',
                'dysthimia',
                'dysthymia',
                'dysthymia',
                'dysthymia disorder',
                'dysthymic',
                'dysthymic dis',
                'dysthymic disorder',
                'dystimea',
                'dystimia',
                'early childhood autism',
                'early infantile autism',
                'eating disord',
                'eating disorder',
                'eating disordet',
                'eating disordr',
                'enxiety',
                'excoriation',
                'excoriation of skin',
                'free-floating anxiety',
                'general anxiety disorder',
                'generalised anxiety disorder',
                'generalized anxiety',
                'generalized anxiety dis',
                'generalized anxiety disorder',
                'generalized anxiety disorder',
                'generalizing anxiety disorder',
                'hoarding disorder',
                'hysterical neurosis',
                'infantile autism',
                'insanity of double form',
                'kannerian autism',
                "kanner's syndrome",
                'kanners syndrome',
                'kanner syndrome',
                'late luteal phase dysphoric disorder',
                'llpdd',
                'major depression',
                'major depression',
                'major depression disorder',
                'major depression disorder (mdd)',
                'major depressive',
                'major depressive dis',
                'major depressive disorder',
                'major depressive disorder nos',
                'major depressive illness',
                'manic depression',
                'manic-depression',
                'manic depression bipolar',
                'manic depressive',
                'manic-depressive',
                'manic depressive disorder',
                'manic-depressive disorder',
                'manic depressive illness',
                'manic-depressive illness',
                'manic-depressive mental disorder',
                'manic-depressive psychoses',
                'manic depressive psychosis',
                'manic-depressive psychosis',
                'manic depressive reaction',
                'mdd',
                'menstrual dysphoric disorder',
                'mental depression',
                'mental disease',
                'mental disorder',
                'mental disorder',
                'mental illness',
                'merycism',
                'monopolar depression',
                'neurotic depression',
                'nonautistic',
                'obbsessive compulsive disorder',
                'obsessive compulsion',
                'obsessive compulsive',
                'obsessive-compulsive',
                'obsessive-compulsive behaviour',
                'obsessive compulsive dis',
                'obsessive-compulsive dis',
                'obsessive compulsive disorder',
                'obsessive-compulsive disorder',
                'obsessive-compulsive disorder',
                'obsessive-compulsiveness',
                'obsessive-compulsive neuroses',
                'obsessive compulsive neurosis',
                'obsessive-compulsive neurosis',
                'obsessive compulsive personality',
                'obsessive-compulsive personality',
                'obsessive compulsive personality disorder',
                'obsessive-compulsive personality disorder',
                'obsessive-compulsive syndrome',
                'obsessive compuslive disorder',
                'obsessive neurotics',
                'ocd',
                'o.c.d.',
                'oc disorder',
                'over-compulsive disorder',
                'overeating disorder',
                'panic anxiety syndrome',
                'panic disord',
                'panicdisorder',
                'panic disorder',
                'panic disorder',
                'panic disorder nos',
                'panic dissorder',
                'paranoid schizophrenia',
                'paranoid schizophrenic',
                'pathological eating disorder',
                'pervasive developmental disorders',
                'phobia social',
                'pipolar',
                'pmdd',
                'post-traumatic neuroses',
                'posttraumatic neuroses',
                'post traumatic stress',
                'post-traumatic stress',
                'posttraumatic stress',
                'post traumatic stress dis',
                'posttraumatic stress dis',
                'post traumatic stress disorder',
                'post traumatic stress disorder',
                'post-traumatic stress disorder',
                'post-traumatic stress disorder',
                'post-traumatic stress disorder',
                'posttraumatic stress disorder',
                'posttraumatic stress disorder',
                'post-traumatic stress disorder (ptsd)',
                'post-traumatic stress reaction',
                'post traumatic stress syndrome',
                'post-traumatic stress syndrome',
                'posttraumatic stress syndrome',
                'post-traumatic syndrome',
                'premenstrual disphoric disorder',
                'premenstrual dysphoric disorder',
                'premenstrual dysphoric disorder',
                'premenstrual dysphoric syndrome',
                'psychosis manic depressive',
                'psychosis manic-depressive',
                'psychothemia',
                'psychothymia',
                'ptsd',
                'ptsd',
                'ptsr',
                'ptss',
                'rapid cycling',
                'rapid-cycling bipolar',
                'rapid cycling bipolardepression',
                'reactive depression',
                'recurrent depressive disorder',
                'rumination',
                'rumination dis',
                'rumination disorder',
                'rumination disorder',
                'rumination (eating disorder)',
                'rumination syndrome',
                'schiizophrenia',
                'schitzo',
                'schitzophrenia',
                'schizo',
                'schizofrenia',
                'schizophernia',
                'schizophren',
                'schizophrene',
                'schizophrenia',
                'schizophrenia disorder',
                'schizophreniak',
                'schizophrenic',
                'schizophrenic',
                'schizophrenic dis',
                'schizophrenic disorder',
                'schizophrenic narcissism',
                'schyzophrenia',
                'scizophrenia',
                'separation anxiety',
                'separation anxiety dis',
                'separation anxiety disorder',
                'separation anxiety disorder',
                'seperation anxiety',
                'sever depression',
                'severe depression',
                'severe depression',
                'severe depressive',
                'shizophrenia',
                'shizophrenic',
                'skin excoriation',
                'skitsafrantic',
                'skitzafrenic',
                'skitzophrenia',
                'social anxie',
                'social anxieties',
                'social anxiety',
                'social anxiety',
                'social anxiety disorder',
                'socialphobia',
                'social phobia',
                'social phobia',
                'social phobia disorder',
                'socialphobic',
                'social phobic',
                'suffer from',
                'suffering from',
                'tramatic stress disorder',
                'traumatic stress disorder',
                'trichollomania',
                'trichotilimania',
                'trichotillomania',
                'trichotillomania',
                'tricho-tillomania',
                'trichotillomaniac',
                'trichotillomanias',
                'trichotillomannia',
                'trichotillosis',
                'trichotilomania',
                'trichtillomania',
                'tricotillomaniaptsd',
                'unipolar depression',
                'unipolar depressive disorder',
                'unipolar major depression',
                'unspecified schizophrenia']
    ## Positive Patterns
    pos_patterns =  ['i am diagnosed with',
                'i got diagnos',
                'i just got diagnos',
                'i have been diagnos',
                'i was diagnos',
                'i have a diagnos',
                'i have diagnos',
                "i've been diagnos",
                'i suffer from clinically diagnos',
                'i suffer from diagnos',
                "i've been diagnosed with",
                'my doctor diagnosed me',
                'she diagnosed me',
                'he diagnosed me',
                'they diagnosed me',
                'recently diagnosed me as',
                'i was recently diagnos',
                'i have recently been diagnos',
                'i have been recently diagnos',
                'until i was diagnosed this year',
                'last year i was diagnos',
                'i have honestly diagnosed',
                'i have been recently diagnos',
                'i have recently been diagnos',
                'i was recently diagnos',
                'they diagnosed me with',
                'as someone with a diagnos',
                'im diagnos',
                "i'm diagnos",
                'i was _doctor diagnos',
                "i've been _doctor diagnos",
                'i have been _doctor diagnos',
                'i was just diagnos',
                "i've been recently diagnos",
                "i've recently been diagnos",
                "i've just been diagnos",
                "i've been diagnos",
                "i've only recently been diagnos",
                "i've only been diagnos",
                '_doctor who diagnosed and medicated me',
                '_doctor diagnosed me',
                'i have _doctor diagnosed',
                'i am _doctor diagnosed',
                'i was first diagnos',
                'i only got diagnos',
                'following my diagnos',
                'after my diagnos',
                'i also have been diagnos',
                'i was given a diagnos',
                'who diagnosed me',
                "i'm also diagnos",
                'my recent diagnosis',
                'mine is diagnosed',
                'i got sick and was diagnosed',
                'i became sick and was diagnosed',
                'they diagnosed me',
                'she diagnosed me',
                'he diagnosed me',
                'they just diagnosed me',
                'she just diagnosed me',
                'he just diagnosed me',
                'they recently diagnosed me',
                'she recently diagnosed me',
                'he recently diagnosed me',
                'i had been diagnosed',
                'i have also been diagnosed',
                "i've been depressed and diagnosed",
                'i got a _doctor diagnos',
                'i got _condition diagnos',
                'i got a _condition diagnos',
                'my _condition diagnosis',
                "i've got a _condition diagnosis",
                'i have a _condition diagnosis',
                "i've a _condition diagnosis",
                'my official diagnosis of',
                "since being diagnosed i've",
                "since diagnosed i've",
                'i was also diagnosed',
                '_doctor has diagnosed my',
                'i have only recently been diagnos',
                'i have recently been diagnos',
                'only recently have i been diagnos',
                "i've been seeing a _doctor and been diagnos",
                'i am diagnosed _condition',
                "i've suffered with diagnosed",
                'i have diagnosed _condition',
                'i also have diagnosed _condition',
                'my _condition diagnosis',
                'i was then diagnosed with',
                'i was diagnosed with',
                "i'm recently diagnosed",
                "i've already been diagnosed",
                "i've been diagnosed",
                'i was very recently diagnosed',
                "i'm very recently diagnosed",
                'i got my diagnosis of',
                'my _condition diagnosis',
                'i was ultimately diagnosed',
                'my only _doctor diagnosis',
                'my _doctor diagnosis',
                'depressive episode that got me diagnosed',
                'i went to see a _doctor, was diagnosed',
                'i went to see a _doctor was diagnosed',
                'i have been previously diagnosed',
                'i eventually got a diagnosis',
                'i finally got a diagnosis',
                'i am diagnosed _condition',
                'i ended up being diagnosed',
                'i was eventually diagnosed',
                'i had gotten the diagnosis',
                'i received the diagnosis',
                'i have ended up being diagnosed',
                'i have been diagnosed',
                'i was originally diagnosed',
                'i am recently diagnosed',
                'i have had diagnosed',
                'my recently diagnosed _condition',
                'i have a couple _condition diagnos',
                'i have a _condition diagnos',
                "i've since been diagnosed",
                'i have several other _condition diagnosed',
                'i have many other _condition diagnosed',
                'i have several _condition diagnosed',
                'i have many _condition diagnosed',
                'i had already been diagnosed',
                'i had been diagnosed',
                'i got _condition diagnosis',
                'i had a _doctor diagnose me',
                'i even went to a _doctor and got diagnosed',
                'i even went to the _doctor and got diagnosed',
                'i went to a _doctor and got diagnosed',
                'i went to the _doctor and got diagnosed',
                'i have been _condition, with a diagnosis',
                'i have been _condition with a diagnosis',
                'i have _condition, diagnosed',
                'i have _condition diagnosed',
                'my _doctor has diagnosed me',
                "i've been struggling with my diagnosis",
                'i have _condition, which was only recently diagnosed',
                'i have _condition, which was recently diagnosed',
                'i have _condition which was only recently diagnosed',
                'i have _condition which was recently diagnosed',
                'i went to the _doctor, got diagnosed',
                'i went to the _doctor got diagnosed',
                'i went to _doctor, got diagnosed',
                'i went to _doctor got diagnosed',
                'i went to the _doctor, get diagnosed',
                'i went to the _doctor get diagnosed',
                'i went to _doctor, get diagnosed',
                'i went to _doctor get diagnosed',
                'i saw a _doctor after being diagnosed',
                'led my _doctor to my current diagnosis',
                'led my _doctor to my diagnosis',
                "i've tried since my diagnosis",
                "i've tried since being diagnosed",
                "i've tried after my diagnosis",
                "i've tried after being diagnosed"]
    ## Negative Patterns
    neg_patterns = ['not formally diagnos',
                    'not diagnos',
                    'not technically diagnosed',
                    'never been diagnos',
                    'chooses not to be diagnos',
                    'never clinically diagnos',
                    'self diagnos',
                    'her recent cancer diagnos',
                    "_ref currently doesn't have a diagnos",
                    'what is your diagnos',
                    'until i get diagnos',
                    "i haven't been diagnos",
                    'diagnos her',
                    "i hadn't been diagnos",
                    'diagnos people',
                    "i don't expect a diagnos",
                    'how you get diagnos',
                    'i dont have any diagnos',
                    'i have not been diagnos',
                    'they were diagnos',
                    'fear a diagnos',
                    "i'll be diagnos",
                    'to get a diagnos',
                    'to be diagnos',
                    'no diagnos',
                    'policy against diagnosis',
                    'who have been diagnos',
                    'who have actually been diagnos',
                    "wasn't diagnos",
                    "wasn't clinically diagnos",
                    "wasn't formally diagnos",
                    "i'm not a diagnos",
                    '_ref was then diagnos',
                    '_ref is diagnos',
                    '_ref has recently been diagnos',
                    '_ref has been recently dianos',
                    '_ref was just dianos',
                    '_ref has been dianos',
                    "he's diagnos",
                    "she's diagnos",
                    '_ref does have diagnos',
                    '_ref been diagnos',
                    '_ref has been diagnos',
                    '_ref being dianos',
                    '_ref got diagnos',
                    'no formal diagnos',
                    'not received any diagnos',
                    'not looking for a diagnos',
                    'bever gad duagbis',
                    'diagnostic analysis',
                    'to diagnose or fix',
                    'diagnostics',
                    'diagnostic test',
                    'trying to get diagnos',
                    'help me diagnos',
                    'any help diagnos',
                    'costs associated with diagnos',
                    'have never sought diagnos',
                    'not yet diagnos',
                    "wasn't actually diagnos",
                    "haven't been diagnos",
                    'have not been diagnos',
                    'who has been diagnos',
                    'never diagnosed me',
                    'this is an informal diagnosis',
                    'this is a self diagnosis',
                    'this is a self-diagnosis',
                    "you guys can't diagnose me",
                    "you can't diagnose me",
                    "you can't make a diagnosis",
                    'never actually diagnosed',
                    'never been officially diagnos',
                    'i almost wish i had a _condition diagnosis',
                    'nor am i diagnos']
    ## Expand Patterns
    all_patterns = []
    if use_mh:
        all_patterns.extend(mh_terms)
    psets = []
    if use_pos:
        psets.append(pos_patterns)
    if use_neg:
        psets.append(neg_patterns)
    for pset in psets:
        for p in pset:
            if "_" in p:
               p_sep = p.split()
               n = len(p_sep) - 1
               exp_match = [i for i, j in enumerate(p_sep) if j.startswith("_")][0]
               exp_match_fillers = GEORGETOWN_EXPANSION_MAPPING[p_sep[exp_match].rstrip(",")]
               for emf in exp_match_fillers:
                   if p_sep[exp_match].endswith(","):
                       emf += ","
                   emf_pat = " ".join(p_sep[:exp_match] + [emf] + p_sep[min(n, exp_match+1):])
                   all_patterns.append(emf_pat)
            else:
                all_patterns.append(p)
    all_patterns = set(all_patterns)
    return all_patterns

###################
### Modeling Pipelines
###################

## Modeling Pipelines
def model_subreddits(X,
                     y,
                     subreddits,
                     filtered_subs):
    """

    """
    ## Isolate Data
    subreddit_mask = [i for i, sub in enumerate(subreddits) if sub.lower() not in filtered_subs]
    subreddits_filtered = list(map(lambda i: subreddits[i], subreddit_mask))
    X_filtered = X[:, subreddit_mask]
    ## Count Number of Users Who Lose All Data With Filtering
    filtered_users = (X_filtered.sum(axis=1) == 0).sum()
    ## Train/Test Splits
    splitter = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    splits = list(splitter.split(X_filtered, y))
    ## Run Cross Validation
    cv_results = []
    coefs = []
    for fold, (train_, test_) in enumerate(splits):
        print(f"Starting Fold {fold+1}/5")
        ## Isolate Split Data
        X_train, y_train = X_filtered[train_], y[train_]
        X_test, y_test = X_filtered[test_], y[test_]
        ## Filtered Users
        train_null_users =  (X_train.sum(axis=1) == 0).sum()
        test_null_users = (X_test.sum(axis=1) == 0).sum()
        ## Preprocess (Tfidf)
        t = TfidfTransformer()
        X_train = t.fit_transform(X_train)
        X_test = t.transform(X_test)
        ## Fit Model
        model = LogisticRegression(solver="lbfgs", max_iter=1000)
        model = model.fit(X_train, y_train)
        coefs.append(pd.Series(model.coef_[0], index=subreddits_filtered))
        ## Get Predictions
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        ## Score
        for tset, y_pred, y_true, null in zip(["train","test"],
                                        [y_pred_train, y_pred_test],
                                        [y_train, y_test],
                                        [train_null_users, test_null_users]):
            p, r, f, s = metrics.precision_recall_fscore_support(y_true, y_pred, average="binary", pos_label="depression")
            accuracy = metrics.accuracy_score(y_true, y_pred)
            cv_results.append({"fold":fold,
                               "group":tset,
                               "precision":p,
                               "recall":r,
                               "fscore":f,
                               "accuracy":accuracy,
                               "null_users":null})
    ## Format Results
    cv_results = pd.DataFrame(cv_results)
    coefs = pd.concat(coefs, axis=1).mean(axis=1).sort_values(ascending=False)
    ## Average Results
    avg_cv_results = cv_results.drop(["fold"],axis=1).groupby(["group"]).mean()
    std_cv_results = cv_results.drop(["fold"],axis=1).groupby(["group"]).std()
    return cv_results, avg_cv_results, std_cv_results, filtered_users, coefs

def model_language(filenames,
                   metadata,
                   filtered_subs=set(),
                   filtered_language=set(),
                   min_usage=10,
                   min_date=None,
                   max_date=None):
    """

    """
    ## Date Boundaries
    if min_date is not None and isinstance(min_date,str):
        min_date=pd.to_datetime(min_date)
    if max_date is not None and isinstance(max_date,str):
        max_date=pd.to_datetime(max_date)
    ## Load Language Data
    mp = Pool(8)
    func = partial(get_language_counts,
                   filtered_subs=filtered_subs,
                   filtered_language=filtered_language,
                   min_date=min_date,
                   max_date=max_date)
    res = dict(tqdm(mp.imap_unordered(func, filenames), total=len(filenames), file=sys.stdout))
    mp.close()
    ## Vectorize
    filenames = sorted(res)
    vocab = sorted(set(flatten(res.values())))
    vocab2vec = create_dict_vectorizer(vocab)
    X = vstack(list(map(lambda f: vocab2vec.transform(res[f]), filenames)))
    y = metadata.set_index("source")["depression"].loc[filenames].values
    ## Count Number of Users Who Lose All Data With Filtering
    filtered_users = (X.sum(axis=1) == 0).sum()
    ## Train/Test Splits
    splitter = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    splits = list(splitter.split(X, y))
    ## Run Cross Validation
    cv_results = []
    coefs = []
    for fold, (train_, test_) in enumerate(splits):
        print(f"Starting Fold {fold+1}/5")
        ## Isolate Split Data
        X_train, y_train = X[train_], y[train_]
        X_test, y_test = X[test_], y[test_]
        ## Vocab Threshold Filtering
        vocab_mask = np.where((X_train>0).sum(axis=0) >= min_usage)[1]
        vocab_filtered = [vocab[v] for v in vocab_mask]
        X_train = X_train[:, vocab_mask]
        X_test = X_test[:, vocab_mask]
        ## Filtered Users
        train_null_users =  (X_train.sum(axis=1) == 0).sum()
        test_null_users = (X_test.sum(axis=1) == 0).sum()
        ## Preprocess (Tfidf)
        t = TfidfTransformer()
        X_train = t.fit_transform(X_train)
        X_test = t.transform(X_test)
        ## Fit Model
        model = LogisticRegression(solver="lbfgs", max_iter=1000)
        model = model.fit(X_train, y_train)
        coefs.append(pd.Series(model.coef_[0], index=vocab_filtered))
        ## Get Predictions
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)
        ## Score
        for tset, y_pred, y_true, null in zip(["train","test"],
                                        [y_pred_train, y_pred_test],
                                        [y_train, y_test],
                                        [train_null_users, test_null_users]):
            p, r, f, s = metrics.precision_recall_fscore_support(y_true, y_pred, average="binary", pos_label="depression")
            accuracy = metrics.accuracy_score(y_true, y_pred)
            cv_results.append({"fold":fold,
                               "group":tset,
                               "precision":p,
                               "recall":r,
                               "fscore":f,
                               "accuracy":accuracy,
                               "null_users":null})
    ## Format Results
    cv_results = pd.DataFrame(cv_results)
    coefs = pd.concat(coefs, axis=1, sort=True).mean(axis=1).sort_values(ascending=False)
    ## Average Results
    avg_cv_results = cv_results.drop(["fold"],axis=1).groupby(["group"]).mean()
    std_cv_results = cv_results.drop(["fold"],axis=1).groupby(["group"]).std()
    return cv_results, avg_cv_results, std_cv_results, filtered_users, coefs

###################
### Globals
###################

## Initialize Tokenizer
TOKENIZER = Tokenizer(keep_case=False,
                      negate_handling=False,
                      negate_token=False,
                      upper_flag=False,
                      keep_punctuation=False,
                      keep_numbers=False,
                      expand_contractions=True,
                      keep_user_mentions=False,
                      keep_pronouns=True,
                      keep_url=False,
                      keep_hashtags=False,
                      keep_retweets=False,
                      emoji_handling=None)

## Comparison Groups
filter_subs = {"None": set([]),
               "Depression":set(["depression"]),
               "RSDD":set(["addiction",
                           "alcoholism",
                           "anger",
                           "bipolarreddit",
                           "bpd",
                           "depersonalization",
                           "depression",
                           "dp_dr",
                           "dpdr",
                           "eatingdisorders",
                           "feelgood",
                           "getting_over_it",
                           "hardshipmates",
                           "makemefeelbetter",
                           "mentalhealth",
                           "panicparty",
                           "psychoticreddit",
                           "ptsd",
                           "rapecounseling",
                           "socialanxiety",
                           "stopselfharm",
                           "suicidewatch",
                           "survivorsofabuse",
                           "traumatoolbox"]),
               "SMHD":set(
                   ['addiction',
                    'alcoholism',
                    'anger',
                    'depersonalization',
                    'dp_dr',
                    'dpdr',
                    'feelgood',
                    'hardshipmates',
                    'makemefeelbetter',
                    'mentalhealth',
                    'psychiatry',
                    'psychoticreddit',
                    'rapecounseling',
                    'selfharm',
                    'stopselfharm',
                    'survivorsofabuse',
                    'traumatoolbox',
                    'suicidewatch',
                    'sanctionedsuicide',
                    'tourettes',
                    'bpd',
                    'bpdlovedones',
                    'bpdsoffa',
                    'depression',
                    'depressed',
                    'depression_help',
                    'getting_over_it',
                    'depressionregimens',
                    'pmdd',
                    'dysthymia',
                    'adhd',
                    'add',
                    'adhd_anxiety',
                    'adhd_coaching',
                    'twoxadhd',
                    'adhdmeme',
                    'adhdwomen',
                    'parentsofadhd',
                    'anxiety',
                    'socialanxiety',
                    'socialphobia',
                    'agoraphobia',
                    'panicdisorder',
                    'panicattack',
                    'panicparty',
                    'ptsd',
                    'cptsd',
                    'ptsdcombat',
                    'schizophrenia',
                    'schizoid',
                    'bipolar',
                    'bipolar2',
                    'bipolarreddit',
                    'cyclothymia',
                    'bipolarart',
                    'bipolarsos',
                    'manicdepression',
                    'ocd',
                    'rocd',
                    'ocpd',
                    'eatingdisorders',
                    'fuckeatingdisorders',
                    'eating_disorders',
                    'ednos',
                    'bingeeatingdisorder',
                    'proedmemes',
                    'selectiveeating',
                    'bulimia',
                    'fatpeoplestories',
                    'proed',
                    'myproana',
                    'thinspo',
                    'thinspocommunity',
                    'malethinspo',
                    'autism',
                    'aspergers',
                    'autistic',
                    'autisticadults']),
               "All Mental Health":set([
                            "depression",
                            "suicidewatch",
                            "anxiety",
                            "selfharm",
                            "mentalhealth",
                            "lonely",
                            "depression_memes",
                            "socialanxiety",
                            "depression_help",
                            "depressionmemes",
                            "narcissism",
                            "emotionalabuse",
                            "bipolar",
                            "bpd",
                            "hikikomori",
                            "madover30",
                            "madeofstyrofoam",
                            "drugs",
                            "adhd",
                            "npd",
                            "depressed",
                            "paranoia",
                            "ocd",
                            "dermatillomania",
                            "anxietydepression",
                            "selfharmscars",
                            "bipolarsos",
                            "edanonymous",
                            "insomnia",
                            "cptsd",
                            "nailbiting",
                            "cutters",
                            "mentalillness",
                            "antidepressants",
                            "sadness",
                            "suicidememe",
                            "adultselfharm",
                            "collapsesupport",
                            "ihatemyself",
                            "antinatalism",
                            "loneliness",
                            "benzodiazepines",
                            "ptsd",
                            "sad",
                            "dpdr",
                            "schizotypal",
                            "mentalhealthuk",
                            "pessimism",
                            "dsbm",
                            "proanampa",
                            "overeatersanonymous",
                            "depression_de",
                            "hocd",
                            "bodydysmorphia",
                            "therapy",
                            "depressionregimens",
                            "bingeeatingdisorder",
                            "proed",
                            "schizophrenia",
                            "bipolar2",
                            "stopselfharm",
                            "aspergers",
                            "ddlgpersonals",
                            "lonely_meetup",
                            "edanonymousadults",
                            "traumaticchildhood",
                            "anxietysuccess",
                            "pornaddiction",
                            "inceldate",
                            "benzedrex",
                            "ptsdcombat",
                            "bipolar_irl",
                            "transsupport",
                            "chronicfatigue",
                            "bulimia",
                            "anorexianervosa",
                            "nihilism",
                            "bipolarreddit",
                            "avpd",
                            "overcoming",
                            "psychonaut",
                            "trollcoping",
                            "opiates",
                            "lexapro",
                            "addiction",
                            "autisticadults",
                            "skinpicking",
                            "autismtranslated",
                            "opiatewithdrawal",
                            "researchingdepression",
                            "suicide_help",
                            "thanatophobia",
                            "tackle_depression",
                            "ddlglewds",
                            "selffarmpics",
                            "ineedhelp",
                            "abusiverelationships",
                            "narcissisticabuse",
                            "incelswithouthate",
                            "abuse",
                            "borderlinepdisorder",
                            "anger",
                            "misanthropy",
                            "compulsiveskinpicking",
                            "suicidebereavement",
                            "sanctionedsuicide",
                            "dxm",
                            "zoloft",
                            "dissociation",
                            "anxietyhelp",
                            "selfhate",
                            "death",
                            "intrusivethoughts",
                            "radicalmentalhealth",
                            "eatingdisorderhope",
                            "downsyndrome",
                            "undiagnosed",
                            "iwanttokillmyself",
                            "psychedelictherapy",
                            "ocpd",
                            "clinicalpsychology",
                            "bipolardisorderreddit",
                            "overlyspecificedmemes",
                            "opiateswriters",
                            "teensuicide",
                            "erectiledysfunctioned",
                            "bipolarart",
                            "genderdysphoria",
                            "abusevictims",
                            "depersonalization",
                            "horriblydepressing",
                            "psychosis",
                            "bpdmemes",
                            "schizoid",
                            "mmfb",
                            "getting_over_it",
                            "bpdlovedones",
                            "pmdd",
                            "anxietymemes",
                            "healthanxiety",
                            "survivorsofabuse",
                            "fuckeatingdisorders",
                            "bodyacceptance",
                            "adderall",
                            "agoraphobia",
                            "rapecounseling",
                            "adhd_anxiety",
                            "collapse",
                            "panicattack",
                            "effexor",
                            "tretinoin",
                            "suicidalthoughts",
                            "mentalhealthsupport",
                            "adultsurvivors",
                            "eatingdisorders",
                            "autism",
                            "talktherapy",
                            "ddlg",
                            "lifeafternarcissism",
                            "ssris",
                            "alone",
                            "emetophobia",
                            "adultdepression",
                            "sociopath",
                            "hppd",
                            "cptsdmemes",
                            "dysmorphicdisorder",
                            "rape",
                            "selfharmpics",
                            "obsessive",
                            "nervous",
                            "melancholy",
                            "ocdmemes",
                            "schizoaffective",
                            "abusiveparents",
                            "helpmecope",
                            "depressionrecovery",
                            "proedmemes",
                            "antipsychiatry",
                            "derealization",
                            "suicidology",
                            "depressedvirgins",
                            "stress",
                            "prozac",
                            "psychopaths",
                            "therapists",
                            "aspergers_dating",
                            "ddlgconfess",
                            "alzheimers",
                            "suicidenotes",
                            "teenagesuicidewatch",
                            'thecountdowntosuicide',
                            'askatherapist',
                            'foreveralone',
                            'suicidalpeople',
                            'cripplingalcoholism',
                            'borderlinepdisorderedanonymous',
                            'mdmatherapy',
                            'stopdrinking',
                            'hardshipmates',
                            'griefsupport',
                            'benzorecovery',
                            'deppression',
                            'foreveralonedatingrape',
                            'psychoticreddit',
                            'artistswithdepression',
                            'opiatesrecovery',
                            'edanonymemes',
                            'needafriend',
                            'exnocontact',
                            'traumatoolbox',
                            'panicparty',
                            'dp_dr', 
                            'makemefeelbetter',
                            'feelgood',
                            'alcoholism',
                            'selectiveeating',
                            'tourettes',
                            'bpdsoffa',
                            'dysthymia',
                            'bipolarart',
                            'psychiatry',
                            'adhdmeme',
                            'rocd',
                            'autistic',
                            'eating_disorders',
                            'adhd_coaching',
                            'socialphobia',
                            'cyclothymia',
                            'fatpeoplestories',
                            'twoxadhd',
                            'manicdepression',
                            'add',
                            'malethinspo',
                            'panicdisorder',
                            'adhdwomen',
                            'myproana',
                            'thinspo',
                            'ednos',
                            'parentsofadhd',
                            'ocpd',
                            'thinspocommunity'])
            }

filter_language = {"None":set(),
                   "RSDD":create_rsdd_language_patterns(True, False, False),
                   "SMHD":create_smhd_language_patterns(True, False, False)}
